#!/bin/bash

echo "🔧 ARKA - Utilidades para Ubuntu/Linux"
echo "======================================"
echo ""

# Make all shell scripts executable
echo "📝 Haciendo todos los scripts ejecutables..."
chmod +x *.sh
echo "✅ Scripts ejecutables"

echo ""
echo "📋 Scripts disponibles:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 EJECUCIÓN:"
echo "  ./start-all-services.sh           - Iniciar todos los microservicios"
echo "  ./start-load-balancing.sh         - Configurar load balancing"
echo "  ./start-with-config-server.sh     - Iniciar con Config Server"
echo "  ./start-circuit-breaker-cli.sh    - CLI interactiva Circuit Breaker"
echo ""
echo "🧪 TESTING:"
echo "  ./test-circuit-breaker.sh         - Probar Circuit Breakers"
echo "  ./test-config-server.sh           - Probar Config Server"
echo ""
echo "⚙️  CONFIGURACIÓN:"
echo "  ./upload-config.sh                - Subir configs a GitHub"
echo "  ./stop-all-services.sh            - Parar todos los servicios"
echo "  ./check-services.sh               - Verificar estado de servicios"
echo ""
echo "🐳 DOCKER:"
echo "  ./docker-start.sh                 - Iniciar con Docker Compose"
echo "  ./docker-stop.sh                  - Parar Docker Compose"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Para más información sobre cada script, ábrelo con un editor de texto"
echo ""
echo "🎯 Uso típico:"
echo "1. ./start-all-services.sh         # Iniciar sistema completo"
echo "2. ./check-services.sh             # Verificar que todo esté OK"
echo "3. ./test-circuit-breaker.sh       # Probar funcionalidades"
echo "4. ./stop-all-services.sh          # Parar todo cuando termines"
